routes/web.php
<?php
use App\Post;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',"PostController@index");

Route::resource("posts","PostController");


//ログイン中のユーザのみ許可
// Route::group(['middleware' => ['auth']], function () {

// });

// 権限にWriteが付与されているユーザのみ許可
Route::group(['middleware' => ['permission:Write']], function () {
    Route::get('users/export', 'UserController@export');
    Route::resource("users","UserController");
});

// 権限にReadが付与されているユーザのみ許可
Route::group(['middleware' => ['permission:Read']], function () {
    Route::resource("users","UserController", ['only' => ['index', 'show']]);
});

Route::get('/home', 'HomeController@index');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles; // laravel-permission

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

use App\Exports\UsersExport;
use Maatwebsite\Excel\Facades\Excel;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'asc')->paginate(10);

		return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();

		$rules = [
			'name' => 'required', 
			'email' => 'required',
			'password' => 'required',
			'role' => 'required',
		];

		$validation = \Validator::make($inputs,$rules);

        $user = new User();

		if($validation->fails()) 
			return redirect()->back()->withErrors($validation->errors())->withInput();

        if($user->where('email', $request->input('email'))->exists()) {
            flash('メールアドレスが重複しています')->error();
		    return redirect()->route('users.create');
        }

		$user->name = $request->input("name");
        $user->email = $request->input("email");
        $user->password = $request->input("password");

        $role = Role::find($request->input("role"))['name'];
        //Roleが存在するか
        if(!empty($role))
            $user->syncRoles($role);

		$user->save();

        return redirect()->route('users.index')->with('message', 'Item created successfully.');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $inputs = $request->all();

		$rules = [
			'name' => 'required', 
			'email' => 'required',
			'password' => 'required',
			'role' => 'required',
		];

		$validation = \Validator::make($inputs,$rules);

		if($validation->fails()) 
			return redirect()->back()->withErrors($validation->errors())->withInput();

		$user->name = $request->input("name");
        $user->email = $request->input("email");
        $user->password = $request->input("password");

        $role = Role::find($request->input("role"))['name'];
        //Roleが存在するか
        if(!empty($role))
            $user->syncRoles($role);

		$user->save();

		return redirect()->route('users.index')->with('message', 'Item updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

		flash('Item deleted successfully.')->success();
		return redirect()->route('users.index');
    }

    public function export() 
    {
        return Excel::download(new UsersExport, 'users.xlsx');
    }
}

resources/views/users/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Users / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('users.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                    <label for="name-field">Name</label>
                 <input type="text" id="name-field" name="name" class="form-control" value=""/>
                    @if($errors->has("name"))
                     <span class="help-block">{{ $errors->first("name") }}</span>
                    @endif
                 </div>

                 <div class="form-group @if($errors->has('email')) has-error @endif">
                        <label for="email-field">Email</label>
                     <input type="text" id="email-field" name="email" class="form-control" value=""/>
                        @if($errors->has("email"))
                         <span class="help-block">{{ $errors->first("email") }}</span>
                        @endif
                     </div>

                     <div class="form-group @if($errors->has('password')) has-error @endif">
                            <label for="password-field">Password</label>
                         <input type="text" id="password-field" name="password" class="form-control" value=""/>
                            @if($errors->has("password"))
                             <span class="help-block">{{ $errors->first("password") }}</span>
                            @endif
                         </div>

                         <div class="form-group @if($errors->has('role')) has-error @endif">
                             <label for="role-field">Role</label>
                             <select id="role-field" name="role" class="form-control custom-select">
                                 @foreach ($roles as $role)
                                     <option value="{{$role->id}}">{{$role->name}}</option>
                                 @endforeach
                             </select>
                             @if($errors->has("role"))
                                 <span class="help-block">{{ $errors->first("role") }}</span>
                                @endif
                             </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('users.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/users/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Users / Edit #{{$user->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('users.update', $user->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $user->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>

                    <div class="form-group @if($errors->has('email')) has-error @endif">
                           <label for="email-field">Email</label>
                        <input type="text" id="email-field" name="email" class="form-control" value="{{ is_null(old("email")) ? $user->email : old("email") }}"/>
                           @if($errors->has("email"))
                            <span class="help-block">{{ $errors->first("email") }}</span>
                           @endif
                        </div>

                        <div class="form-group @if($errors->has('password')) has-error @endif">
                               <label for="password-field">Password</label>
                            <input type="text" id="password-field" name="password" class="form-control" value="{{ is_null(old("password")) ? $user->password : old("password") }}"/>
                               @if($errors->has("password"))
                                <span class="help-block">{{ $errors->first("password") }}</span>
                               @endif
                            </div>

                            <div class="form-group @if($errors->has('role')) has-error @endif">
                                <label for="role-field">Role</label>
                                <select id="role-field" name="role" class="form-control custom-select">
                                    @foreach ($roles as $role)
                                        <option value="{{$role->id}}" {{$role->name == $user->getRoleNames()[0] ? 'selected' : ''}}>{{$role->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has("role"))
                                    <span class="help-block">{{ $errors->first("role") }}</span>
                                   @endif
                                </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('users.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/users/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Users
            @role('admin')
            <a class="btn btn-success pull-right" href="{{ route('users.create') }}">
                <i class="glyphicon glyphicon-plus"></i> 
                Create
            </a>
            @endrole
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($users->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th>EMAIL</th>
                            @role('admin')<th>PASSWORD</th>@endrole
                            <th>ROLE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{$user->id}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                @role('admin')<td>{{$user->password}}</td>@endrole
                                <td>{{$user->getRoleNames()[0]}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('users.show', $user->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    @role('admin')
                                        <a class="btn btn-xs btn-warning" href="{{ route('users.edit', $user->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                        <form action="{{ route('users.destroy', $user->id) }}" method="post" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                        </form>
                                    @endrole
                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $users->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

    @auth
    <a class="btn btn-success pull-right" href="{{ action('UserController@export') }}">
        <i class="glyphicon glyphicon-plus"></i> 
        Export Excel
    </a>
    @endauth

@endsection

resources/views/users/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Users / Show #{{$user->id}}</h1>
        @role('admin')
            <form action="{{ route('users.destroy', $user->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="btn-group pull-right" role="group" aria-label="...">
                    <a class="btn btn-warning btn-group" role="group" href="{{ route('users.edit', $user->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                    <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
                </div>
            </form>
        @endrole
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static">{{$user->id}}</p>
                </div>
                <div class="form-group">
                     <label for="title">NAME</label>
                     <p class="form-control-static">{{$user->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="body">EMAIL</label>
                     <p class="form-control-static">{{$user->email}}</p>
                </div>
                @role('admin')
                <div class="form-group">
                    <label for="body">PASSWORD</label>
                    <p class="form-control-static">{{$user->password}}</p>
               </div>
               @endrole
               <div class="form-group">
                   <label for="body">ROLE</label>
                   <p class="form-control-static">{{$user->getRoleNames()[0]}}</p>
              </div>
            </form>

            <a class="btn btn-link" href="{{ route('users.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection